services:
  - type: web
    name: rent-management-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add your Supabase environment variables in Render dashboard
      # Don't put secrets in this file - use Render's Environment Variables section
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY  
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false